language: bash
sudo: required
services: docker
env:
  global:
  - REPO=morpheus65535/bazarr
  - QEMU_VERSION=v2.11.0
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: UBcke3TmrISJiHc//4xeHKnlrlK995C5tySiSSJWDz+sAC6rEAxdQRqeUd7S/3uGrZ6O8cZJuOO8g2wsIxK5pVewhHt0mxrpdWDjsI+NsKb5QG5zjkXXXjzYpPqRI1SGuMXFaXTF6Qal54oMRLBNGmzgXM7TxCOSMsrse3eMEmiZFVNXibcl7NMR4IadPFAn6XyJhulXFotEk6hNqfVwpDEAvD8xZPiGrA845sUNRxSe/U7UPxyVMCot16tnIdl6wtaNij4g5/BMUhRKRRQHamD/p2k1lvS6WIMu5X/PBzw8H3x8kcOKqxkqzctSTYPnqFBxuBDrz0pM1MerCjoyOxEHLDPb7TsaI2/O+yFs+N9lfaMIxzPaLdzlHVxbpRys+J3tD1ypOWsi4+13xkbI3kfOn4BLzT54mPBsemVk50/Hc4ChguSa/6BL95zSe1G3jcm4aoGQxN+2fMysTk4IqwfOvI1pewGk7J4XL0ma5UuMu0vUCEuIcrbqkY4Zgf11EauIuWUteQrgCniuLTiJ4w9N5oANl2KGYWTSwMqB96FiNcB/b54H/rXorDFMb2zx1iOxcJeVoRZxyHP0+wV2VrAi0tU9Q5MxU4OF66x4IMEK4Gm8SqOO3P7fmUXL/TNylfAKVAn/eoxNN91wUQuYWZSMLjuwrJX29oH2NXSYV2g=
  - secure: rM1MCfA/UtGWS9m/AUfK+la/CdULBk8VhV2qhjHXJhwyg/i+P/hMQL0UznHTlPrNpdaGAJiYbI0/vc0OsTfMkvqPqGVfH69Swa/icb724NS3DtkeHt+vjF9AWX77iHMErwwPUJbeFfvWq9PpUqNuWwxblFu89HeoGivNjEldQR/wuCR5ETLpJDloR8G1XOY4wi8ypdUQQgJjBvLzFJcSCn0gwJjj4sBYqzE/sXE2vFbEn2Uzjlirt9Ap2+ChH1P+03modSou8hYI/hDQA9u2MLXer9KghFk+bpl4vmV5+v6iQIttcu6ko1FRD2xbNBz2s/V3+7mk5/KCbPL4SjdXRWPGrxEj1vZC9xNMvm8ZxdUUxPxDcT9i4kTqLyQ2NEHbQBISi0Jqw0S1WNDvFzRSfw7JYiIQW4G5nDzVWrJq7Dmmm/Anof3Uhe6lp+4fz7pUsTLTQaqOqo0pSxobGwDfmiQyJtc/V+6kUZAWIJjqeKgMr1oTULNAQtWjjyQ1Y3yJzTcFQQNcmdIvGhtDCHvNPJdkK0+IRAPjIWWQUOXbtywJPONrOAyClh74XlKTnihPuK9NNFYu04Z9YAbLCc//pVyyeBPEGGtz8Zo1/IAKRS8bScx5jvX95Zkn4N05H3WtxTcNN9w1k9PunW63PArmunTxiaqEtp8VrKqzNbyHdqM=
  matrix:
  - ARCH=amd64
  - QEMU_ARCH=arm ARCH=armhf
  - QEMU_ARCH=aarch64 ARCH=arm64
script:
- if [ "$ARCH" != "amd64" ]; then curl -L -o qemu-$QEMU_ARCH-static https://github.com/multiarch/qemu-user-static/releases/download/${QEMU_VERSION}/qemu-$QEMU_ARCH-static; chmod u+x qemu-$QEMU_ARCH-static; fi
- docker run --rm --privileged multiarch/qemu-user-static:register
- docker build -t $REPO:$COMMIT-$ARCH -f Dockerfile.$ARCH .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [ "$ARCH" == "amd64" ]; then docker tag $REPO:$COMMIT $REPO:latest; fi
- docker tag $REPO:$COMMIT-$ARCH $REPO:$ARCH-latest
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker push $REPO; fi
